# Generated by Django 4.2.1 on 2023-05-20 14:16
from django.db import migrations

import environ

env = environ.Env()
environ.Env.read_env()


def create_superuser(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")

    User.objects.create_superuser(
        email=env("DB_SU_EMAIL"),
        username=env("DB_SU_USERNAME"),
        password=env("DB_SU_PASSWORD"),
    )


def delete_superuser(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")

    admin = User.objects.get(pk=1)
    if admin.is_superuser:
        admin.delete()
    else:
        raise IndexError("User with id=1 is not an admin.")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_superuser, delete_superuser)]
