# Generated by Django 4.2.1 on 2023-06-01 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
