# Generated by Django 4.2.1 on 2023-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(null=True, to="home.category"),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(null=True, to="home.tag"),
        ),
    ]
