# Generated by Django 4.2.1 on 2023-05-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="created",
            new_name="published",
        ),
        migrations.AddField(
            model_name="article",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="content",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.OneToOneField(
                max_length=50,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="home.content",
            ),
        ),
    ]
